var firstName = prompt("What is your first name?")
var lastName = prompt("What is your last name?")
var age = prompt("What is your age?")
var fullName = (firstName + " " + lastName)
alert(fullName + " is a goddess!")
alert("And she's only " + age + "!")
console.log(firstName + " " + lastName + " is a goddess!")
console.log("And she's only " + age + "!")